// <auto-generated />
namespace ReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class upgrade_room : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upgrade_room));
        
        string IMigrationMetadata.Id
        {
            get { return "202007022207183_upgrade_room"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
